import type { Metadata } from "next";
import { getImpactMetrics, getPage } from "../../sanity/lib/data";
import { buildMetadata } from "../../sanity/lib/metadata";
import { PageCta, PageHero, SectionIntro } from "../_components/site";

export async function generateMetadata(): Promise<Metadata> { const page = await getPage("impact"); return buildMetadata(page.seo, "Impact", page.introduction); }

export default async function ImpactPage() {
  const [page, metrics] = await Promise.all([getPage("impact"), getImpactMetrics()]);
  return <main><PageHero label={page.heroLabel} title={page.heroTitle} accent={page.heroAccent} copy={page.introduction} aside={<span className="page-tag">PROPOSED 2026–2029 FRAMEWORK</span>} /><section className="section shell theory-grid"><div><p className="section-label">Theory of change</p><h2>Commercial strength can compound public value.</h2></div><div className="theory-flow">{[["INPUT","Research, products, partnerships and patient capital"],["OUTPUT","Safer supply, validated pilots and stronger local capability"],["OUTCOME","Better hygiene access, cleaner production and lower material loss"],["IMPACT","Healthier communities and more resilient African systems"]].map(([stage, copy]) => <article key={stage}><span>{stage}</span><strong>{copy}</strong></article>)}</div></section><section className="section soft-section"><div className="shell"><SectionIntro label="Measurement architecture" title="Metrics a partner can interrogate." copy="Definitions and evidence sources are established before a project makes public impact claims." /><div className="metric-table" role="table" aria-label="Chemcider impact metrics"><div className="metric-row metric-head" role="row"><span>Theme</span><span>Core indicator</span><span>Evidence source</span></div>{metrics.map((metric) => <div className="metric-row" role="row" key={metric.theme}><strong>{metric.theme}</strong><span>{metric.indicator}</span><span>{metric.evidence}</span></div>)}</div></div></section><section className="section shell"><SectionIntro label="Alignment" title="Connected to globally understood outcomes." copy="Our work maps most directly to six Sustainable Development Goals, while remaining accountable to locally defined needs." /><div className="sdg-grid">{[["03","Good health"],["06","Clean water"],["07","Clean energy"],["09","Industry & innovation"],["12","Responsible production"],["13","Climate action"]].map(([n,t]) => <div key={n}><span>{n}</span><strong>{t}</strong></div>)}</div><p className="target-disclaimer">Targets shown across this site are management ambitions, not achieved results. Baselines, budgets and verification arrangements will be finalised with delivery partners before public reporting.</p></section><PageCta /></main>;
}
