import type { Metadata } from "next";
import Link from "next/link";
import { getPage, getProducts } from "../../sanity/lib/data";
import { buildMetadata } from "../../sanity/lib/metadata";
import { Callout, PageCta, PageHero, SectionIntro } from "../_components/site";

export async function generateMetadata(): Promise<Metadata> { const page = await getPage("products"); return buildMetadata(page.seo, "Products", page.introduction); }

export default async function ProductsPage() {
  const [page, products] = await Promise.all([getPage("products"), getProducts()]);
  return <main><PageHero label={page.heroLabel} title={page.heroTitle} accent={page.heroAccent} copy={page.introduction} aside={<Link className="button button-primary" href="/contact">Request product information ↗</Link>} /><section className="section shell"><SectionIntro label="Current lines" title="A focused foundation for growth." copy="Established categories give Chemcider a commercial base from which to deepen quality systems, distribution and related research." /><div className="product-detail-grid">{products.map((product, index) => <article className={`product-detail-card ${index % 2 === 0 ? "blue" : "mint"}`} key={product.slug}><div className="product-detail-visual"><span>{index % 2 === 0 ? "MS" : "H₂O₂"}</span><small>{product.code} / CHEMCIDER</small></div><div className="product-detail-copy"><span className="status-chip">{product.category}</span><h2>{product.name}</h2><p>{product.summary}</p><dl><div><dt>Channels</dt><dd>{product.channels}</dd></div><div><dt>Specifications</dt><dd>{product.specifications}</dd></div><div><dt>Handling</dt><dd>{product.handling}</dd></div></dl></div></article>)}</div><div className="safety-note"><strong>Important product notice</strong><p>Read and follow the approved label and safety information. Do not ingest. Do not mix with other chemicals. Keep out of reach of children. Product claims and use instructions vary by grade and concentration.</p></div></section><section className="section soft-section"><div className="shell"><SectionIntro label="Product stewardship" title="Trust is built batch by batch." copy="Chemcider’s quality roadmap is designed to make product identity, handling and accountability clear across the value chain." /><div className="callout-grid"><Callout number="01" title="Clear specifications">Grade, concentration, pack and intended-use information are defined before sale.</Callout><Callout number="02" title="Traceable supply">Supplier qualification, batch records and complaint handling form the control backbone.</Callout><Callout number="03" title="Useful safety information">Labels and safety documents are written for real handling decisions, not compliance theatre.</Callout><Callout number="04" title="Responsible expansion">Related products advance only after regulatory, safety and commercial review.</Callout></div></div></section><PageCta /></main>;
}
